#!/bin/zsh

# TODO maybe check for different commits between remote and local

autoload vcs and colors
autoload -U colors && colors

# Load version control information
autoload -Uz vcs_info

precmd() {
	psvar=()
	vcs_info

  START="%F{green}%n@%m%{$reset_color%}:%~"

  zstyle ':vcs_info:git:*' formats '(%b)'
	if [[ -n $vcs_info_msg_0_ ]]; then
    psvar[1]="$vcs_info_msg_0_"
    PROMPT="$START %v
%{$fg[yellow]%}%% "
	else
    PROMPT="$START
%{$fg[yellow]%}%% "
	fi

  #RIGHT="$(date) "
  #RIGHTWIDTH="$(($COLUMNS-${#LEFT}))"
  #print $PROMPT${(l:$RIGHTWIDTH::.:)RIGHT}
}

zstyle ':vcs_info:git:*' formats '(%b)'

#https://opensource.apple.com/source/zsh/zsh-61/zsh/Misc/vcs_info-examples.auto.html
