#!/bin/zsh

# TODO maybe check for different commits between remote and local

## autoload vcs and colors
# autoload -Uz vcs_info
autoload -U colors && colors

# Load version control information
autoload -Uz vcs_info

precmd() {
	psvar=()
	vcs_info

zstyle ':vcs_info:git:*' formats '(%b)'
	if [[ -n $vcs_info_msg_0_ ]]; then
		psvar[1]="$vcs_info_msg_0_"
        PROMPT='%n@%m:%~ %v
%% '
	else
        PROMPT='%n@%m:%~
%% '
	fi
}

zstyle ':vcs_info:git:*' formats '(%b)'

#https://opensource.apple.com/source/zsh/zsh-61/zsh/Misc/vcs_info-examples.auto.html
